# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem "rack"
gem "rack-legacy"
gem "rack-rewrite"
gem "thor"
gem "activesupport"
gem "rb-fsevent"
gem "rb-inotify"
gem "rb-kqueue"
gem "middleman"
gem "middleman-livereload"
gem "middleman-autoprefixer"
